/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import entity.*;
import java.util.Optional;
import java.time.LocalDate;
import java.time.LocalTime;
/**
 *
 * @author mariamishinjiashvili
 */
public class Main extends javax.swing.JFrame {
private static DAO CheckInLocationDAO, PassengerDAO; 
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        refreshCheckInLocationTable();
        refreshPassengerTable();
    }

                                         

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAirpotCRUD = new javax.swing.JTabbedPane();
        jPanelCheckInLocation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCINID = new javax.swing.JLabel();
        jLabelCINStationName = new javax.swing.JLabel();
        jTextFieldCINID = new javax.swing.JTextField();
        jTextFieldCINStationName = new javax.swing.JTextField();
        jButtonCINSave = new javax.swing.JButton();
        jButtonCINUpdate = new javax.swing.JButton();
        jButtonCINDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCheckInLocation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelPID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPFirstname = new javax.swing.JLabel();
        jLabelPCheckinLocationID = new javax.swing.JLabel();
        jLabelPLastName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePassenger = new javax.swing.JTable();
        jTextFieldPID = new javax.swing.JTextField();
        jTextFieldPFirstName = new javax.swing.JTextField();
        jTextFieldPLastName = new javax.swing.JTextField();
        jTextFieldPCheckInLocationID = new javax.swing.JTextField();
        jLabelPDateTime = new javax.swing.JLabel();
        jButtonPSave1 = new javax.swing.JButton();
        jButtonPUpdate = new javax.swing.JButton();
        jButtonPDelete = new javax.swing.JButton();
        dateTimePickerPassengerDateTime = new com.github.lgooddatepicker.components.DateTimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AiportCRUD");

        jTabbedPaneAirpotCRUD.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        jPanelCheckInLocation.setToolTipText("CheckInLocation");

        jLabel1.setText("Please enter the following fields for Check In Location");
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelCINID.setText("ID");
        jLabelCINID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelCINStationName.setText("Station Name");
        jLabelCINStationName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldCINID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldCINID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCINIDActionPerformed(evt);
            }
        });

        jTextFieldCINStationName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldCINStationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCINStationNameActionPerformed(evt);
            }
        });

        jButtonCINSave.setText("Save");
        jButtonCINSave.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonCINSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCINSaveMouseClicked(evt);
            }
        });
        jButtonCINSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCINSaveActionPerformed(evt);
            }
        });

        jButtonCINUpdate.setText("Update");
        jButtonCINUpdate.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonCINUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCINUpdateActionPerformed(evt);
            }
        });

        jButtonCINDelete.setText("Delete");
        jButtonCINDelete.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonCINDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCINDeleteActionPerformed(evt);
            }
        });

        jTableCheckInLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Station Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCheckInLocation.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableCheckInLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCheckInLocationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCheckInLocation);
        if (jTableCheckInLocation.getColumnModel().getColumnCount() > 0) {
            jTableCheckInLocation.getColumnModel().getColumn(0).setResizable(false);
            jTableCheckInLocation.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTableCheckInLocation.getColumnModel().getColumn(1).setResizable(false);
            jTableCheckInLocation.getColumnModel().getColumn(1).setPreferredWidth(23);
        }

        javax.swing.GroupLayout jPanelCheckInLocationLayout = new javax.swing.GroupLayout(jPanelCheckInLocation);
        jPanelCheckInLocation.setLayout(jPanelCheckInLocationLayout);
        jPanelCheckInLocationLayout.setHorizontalGroup(
            jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCINSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCINUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCINDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckInLocationLayout.createSequentialGroup()
                        .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCINID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabelCINStationName)
                                .addGap(4, 4, 4)))
                        .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                                .addComponent(jTextFieldCINStationName, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldCINID, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCheckInLocationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCINDelete, jButtonCINSave, jButtonCINUpdate});

        jPanelCheckInLocationLayout.setVerticalGroup(
            jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanelCheckInLocationLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCINID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCINID))
                .addGap(6, 6, 6)
                .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCINStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCINStationName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCheckInLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCINSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCINUpdate)
                    .addComponent(jButtonCINDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanelCheckInLocationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCINDelete, jButtonCINSave, jButtonCINUpdate});

        jTabbedPaneAirpotCRUD.addTab("Check In Location", jPanelCheckInLocation);

        jLabelPID.setText("ID");
        jLabelPID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel3.setText("Please enter the following fields for Passenger");
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelPFirstname.setText("First Name");
        jLabelPFirstname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelPCheckinLocationID.setText("Check In Location ID");
        jLabelPCheckinLocationID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelPLastName.setText("Last Name");
        jLabelPLastName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTablePassenger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Check In Location ID", "Date-TIme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePassenger.setColumnSelectionAllowed(true);
        jTablePassenger.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTablePassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePassengerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePassenger);
        jTablePassenger.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablePassenger.getColumnModel().getColumnCount() > 0) {
            jTablePassenger.getColumnModel().getColumn(0).setPreferredWidth(-20);
            jTablePassenger.getColumnModel().getColumn(1).setResizable(false);
            jTablePassenger.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTablePassenger.getColumnModel().getColumn(2).setResizable(false);
            jTablePassenger.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTablePassenger.getColumnModel().getColumn(3).setResizable(false);
            jTablePassenger.getColumnModel().getColumn(3).setPreferredWidth(24);
            jTablePassenger.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextFieldPID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldPFirstName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldPFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPFirstNameActionPerformed(evt);
            }
        });

        jTextFieldPLastName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldPLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPLastNameActionPerformed(evt);
            }
        });

        jTextFieldPCheckInLocationID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelPDateTime.setText("Date-Time");
        jLabelPDateTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButtonPSave1.setText("Save");
        jButtonPSave1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonPSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPSave1ActionPerformed(evt);
            }
        });
        jButtonPSave1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPSave1KeyPressed(evt);
            }
        });

        jButtonPUpdate.setText("Update");
        jButtonPUpdate.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonPUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPUpdateActionPerformed(evt);
            }
        });

        jButtonPDelete.setText("Delete");
        jButtonPDelete.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButtonPDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPCheckinLocationID)
                            .addComponent(jLabelPLastName)
                            .addComponent(jLabelPFirstname)
                            .addComponent(jLabelPID)
                            .addComponent(jLabelPDateTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPID)
                            .addComponent(jTextFieldPFirstName)
                            .addComponent(jTextFieldPLastName)
                            .addComponent(jTextFieldPCheckInLocationID)
                            .addComponent(dateTimePickerPassengerDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPID)
                            .addComponent(jTextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPFirstname)
                            .addComponent(jTextFieldPFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPLastName)
                            .addComponent(jTextFieldPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPCheckinLocationID)
                            .addComponent(jTextFieldPCheckInLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPDateTime)
                            .addComponent(dateTimePickerPassengerDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPSave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPaneAirpotCRUD.addTab("Passenger", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAirpotCRUD)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAirpotCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCINStationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCINStationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCINStationNameActionPerformed

    private void jTextFieldCINIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCINIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCINIDActionPerformed

    private void jTextFieldPLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPLastNameActionPerformed

    private void jTextFieldPFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPFirstNameActionPerformed


    private void jButtonCINSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCINSaveActionPerformed
        boolean CINprimarykeyviolation=false;
        if (!jTextFieldCINID.getText().isEmpty()) {
            if(!jTextFieldCINStationName.getText().isEmpty()){
            int inputCINID = Integer.parseInt(jTextFieldCINID.getText().trim());
            String inputStationName = jTextFieldCINStationName.getText().trim();
            
            CINprimarykeyviolation=primaryKeyViolationCheckInLocation(inputCINID);
            if(CINprimarykeyviolation==false){
            addCheckInLocation(inputCINID,inputStationName);
            refreshCheckInLocationTable();
            clearCheckInLocationTextFields();
            }
            }//if 2
            else
            {   
                alert("Station Name cannot be empty, Insert error", "Primary Key Violation");
            }
            
        }//if 1
            
        else
        {
            alert("ID cannot be empty, Insert error","Insert Error");
        }
    }//GEN-LAST:event_jButtonCINSaveActionPerformed

    private void jButtonCINDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCINDeleteActionPerformed
        boolean CINforeignkeyviolation=false;
        if (!jTextFieldCINID.getText().isEmpty()) {
            int inputCINID = Integer.parseInt(jTextFieldCINID.getText().trim());
            String inputStationName = jTextFieldCINStationName.getText().trim();
            CheckInLocation checkInLocation = getCheckInLocation(inputCINID);
            if(checkInLocation.getCheckInLocationID() != -1) {
                CINforeignkeyviolation=foreignKeyViolatioinCheckInLocation(inputCINID);
                if(CINforeignkeyviolation==false){
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deleteCheckInLocation(inputCINID, inputStationName);
                    refreshCheckInLocationTable();
                    clearCheckInLocationTextFields();}}
            
        }
        else{alert("Check-In-Location does not exist", "Delete error");}}
        else{alert("ID cannot be empty", "Delete error");}                                                     

    }//GEN-LAST:event_jButtonCINDeleteActionPerformed

    private void jButtonCINSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCINSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCINSaveMouseClicked

    private void jButtonCINUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCINUpdateActionPerformed
if (!jTextFieldCINID.getText().isEmpty()) {
            if(!jTextFieldCINStationName.getText().isEmpty()){
            int inputCINID = Integer.parseInt(jTextFieldCINID.getText().trim());
            String inputStationName = jTextFieldCINStationName.getText().trim();
            CheckInLocation checkInLocation=getCheckInLocation(inputCINID);
            
            if(checkInLocation.getCheckInLocationID() != -1){
            CheckInLocation mcheckInLocation = new CheckInLocation(inputCINID, inputStationName);
            CheckInLocationDAO.insert(mcheckInLocation);
            updateCheckInLocation(inputCINID,inputStationName);
            refreshCheckInLocationTable();
            }
            else{alert("Check-In-Location does not exist", "Update error"); } }
            else{ alert("Station cannot be empty, Inser error", "Primary Key Violation");}}
        else {alert("ID cannot be empty, Insert error","Update Error");}        
    }//GEN-LAST:event_jButtonCINUpdateActionPerformed

    private void jButtonPSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPSave1ActionPerformed
       boolean primarykeyviolation=false;
       boolean foriegnkeyviolation=false;
        if (!jTextFieldPID.getText().isEmpty()) {
           if(!jTextFieldPFirstName.getText().isEmpty()){
               if(!jTextFieldPLastName.getText().isEmpty()){
                   if(!jTextFieldPCheckInLocationID.getText().isEmpty()){
                       if((!dateTimePickerPassengerDateTime.getDatePicker().getDateStringOrEmptyString().isEmpty()) 
                               && (!dateTimePickerPassengerDateTime.timePicker.getTimeStringOrEmptyString().isEmpty())){
            int inputID = Integer.parseInt(jTextFieldPID.getText().trim());
            String inputFirstName = jTextFieldPFirstName.getText().trim();
            String inputLastName = jTextFieldPLastName.getText().trim();
            int PCINID = Integer.parseInt(jTextFieldPCheckInLocationID.getText().trim());
            String date = dateTimePickerPassengerDateTime.datePicker.getDateStringOrEmptyString() + " " 
                    + dateTimePickerPassengerDateTime.timePicker.getTimeStringOrEmptyString()+":00.0";
            primarykeyviolation = primaryKeyViolationPassenger(inputID);
            if(primarykeyviolation==false){
            foriegnkeyviolation=foreignKeyViolationPassenger(PCINID);
            if(foriegnkeyviolation==false){
            addPassenger(inputID, inputFirstName, inputLastName, PCINID, date);
            refreshPassengerTable();
            clearPassengerTextFields();}}}//if5if6if7
       else{alert("Date-Time cannot be empty", "Insert error");}
       }//if4
       else{alert("Check-In-Location ID cannot be empty", "Insert error");}
       }//if3
       else {alert("Last Name cannot be empty", "Insert error");}
       }//if2
       else {alert("First Name cannot be empty", "Insert error");}
       }//if1
       else {alert("ID cannot be empty", "Insert error");}
    }//GEN-LAST:event_jButtonPSave1ActionPerformed

    private void jButtonPUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPUpdateActionPerformed
        if (!jTextFieldPID.getText().isEmpty()) {
          int inputID = Integer.parseInt(jTextFieldPID.getText().trim());
            String inputFirstName = jTextFieldPFirstName.getText().trim();
            String inputLastName = jTextFieldPLastName.getText().trim();
            int PCINID = Integer.parseInt(jTextFieldPCheckInLocationID.getText().trim());
           
            String date = dateTimePickerPassengerDateTime.datePicker.getDateStringOrEmptyString() + " " + dateTimePickerPassengerDateTime.timePicker.getTimeStringOrEmptyString()+":00.0";
         
           Passenger passenger = getPassenger(inputID);
            if(passenger.getPassengerID() != -1) {
                foreignKeyViolationPassenger(PCINID);
                updatePassenger(inputID, inputFirstName, inputLastName, PCINID, date);
                refreshPassengerTable();
            }
            else
            {
                alert("Order does not exist", "Update error");
            }
        }
        else
        {
            alert("ID cannot be empty", "Update error");
        }
    }//GEN-LAST:event_jButtonPUpdateActionPerformed

    private void jButtonPDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDeleteActionPerformed
         if (!jTextFieldPID.getText().isEmpty()) {
          int inputID = Integer.parseInt(jTextFieldPID.getText().trim());
            String inputFirstName = jTextFieldPFirstName.getText().trim();
            String inputLastName = jTextFieldPLastName.getText().trim();
            int PCINID = Integer.parseInt(jTextFieldPCheckInLocationID.getText().trim());
           
            String date = dateTimePickerPassengerDateTime.datePicker.getDateStringOrEmptyString() + " " + dateTimePickerPassengerDateTime.timePicker.getTimeStringOrEmptyString()+":00.0";
         
           Passenger passenger = getPassenger(inputID);
            if(passenger.getPassengerID() != -1) {
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deletePassenger(inputID, inputFirstName, inputLastName, PCINID, date);
                    refreshPassengerTable();
                    clearPassengerTextFields();}}
            else{alert("Passenger does not exist", "Delete error"); }
        } else
        {
            alert("ID cannot be empty", "Delete error");
        }
    }//GEN-LAST:event_jButtonPDeleteActionPerformed

    private void jTableCheckInLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCheckInLocationMouseClicked
       // TODO add your handling code here:
        int i = jTableCheckInLocation.getSelectedRow();
        TableModel model = jTableCheckInLocation.getModel();
        jTextFieldCINID.setText(model.getValueAt(i, 0).toString());
        jTextFieldCINStationName.setText(model.getValueAt(i, 1).toString());
        
    }//GEN-LAST:event_jTableCheckInLocationMouseClicked

    private void jTablePassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePassengerMouseClicked
        int i = jTablePassenger.getSelectedRow();
        TableModel model = jTablePassenger.getModel();
        jTextFieldPID.setText(model.getValueAt(i, 0).toString());
        jTextFieldPFirstName.setText(model.getValueAt(i, 1).toString());
        jTextFieldPLastName.setText(model.getValueAt(i, 2).toString());
        jTextFieldPCheckInLocationID.setText(model.getValueAt(i, 3).toString());
        String date = model.getValueAt(i, 4).toString();
        LocalDate date1 = LocalDate.of(Integer.parseInt(date.substring(0, 4)) ,
            Integer.parseInt(date.substring(5, 7)), Integer.parseInt(date.substring(8, 10)));
        LocalTime time1 = LocalTime.of(Integer.parseInt(date.substring(11, 13)), Integer.parseInt(date.substring(14, 16)));
        dateTimePickerPassengerDateTime.datePicker.setDate(date1);
        dateTimePickerPassengerDateTime.timePicker.setTime(time1);

    }//GEN-LAST:event_jTablePassengerMouseClicked

    private void jButtonPSave1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPSave1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPSave1KeyPressed
 
  public void alert(String msg, String title) {
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }
 
    public boolean primaryKeyViolationCheckInLocation(int id) {
        
        if(getCheckInLocation(id).getCheckInLocationID() != -1) {
            alert("Another Check-In-Location already exists with same CheckInLocation ID, please try another CheckInLocation ID", "Primary Key Violation");
       return true;
        }
    return false;
    }
    public boolean foreignKeyViolatioinCheckInLocation(int id){
        List<Passenger> passengers = PassengerDAO.getAll();
        for (Passenger passenger : passengers) {
        if (passenger.getCheckInLocationID() == id) {
            alert("This station can not be delete, it is in use with a passenger","Foreign Key Violation");
            return true;
        }}
       return false;
    }
     public boolean primaryKeyViolationPassenger(int id) {
       
        if(getPassenger(id).getPassengerID() != -1) {
            alert("Another passenger already exists with same Passenger ID, please try another Passenger ID", "Primary Key Violation");
     return true;
        }
        return false;
    }
    public boolean foreignKeyViolationPassenger(int id) {
        if(getCheckInLocation(id).getCheckInLocationID() == -1) {
            alert("CheckInLocation ID does not exist, please re-enter", "Foreign Key Violation");
        return true;
        }
        return false;
    }
  
    /*
      * CheckInLocation CRUD FUNCTIONS
    */
    private static void addCheckInLocation(int id, String StationName) {
        CheckInLocation checkInLocation;
        checkInLocation = new CheckInLocation(id, StationName);
        CheckInLocationDAO.insert(checkInLocation);
    }
    
    private static void updateCheckInLocation(int id, String StationName) {
        CheckInLocation checkInLocation;
        checkInLocation = new CheckInLocation(id, StationName);
        CheckInLocationDAO.update(checkInLocation);
    }
    
    private static void deleteCheckInLocation(int id, String StationName) {
        CheckInLocation checkInLocation;
        checkInLocation = new CheckInLocation(id, StationName);
        CheckInLocationDAO.delete(checkInLocation);
    }
    
    static CheckInLocation getCheckInLocation(int id) {
        Optional<CheckInLocation> checkInLocations = CheckInLocationDAO.get(id);
        return checkInLocations.orElseGet(() -> new CheckInLocation(-1, "Non-exist"));
    }
    
    /**
     * Passenger CRUD FUNCTIONS
    */
    private static void addPassenger(int ID, String FirstName, String LastName, int CheckInLocationID, String DateTime) {
        Passenger passenger;
        passenger = new Passenger(ID, FirstName, LastName, CheckInLocationID, DateTime);
        PassengerDAO.insert(passenger);
    }
    
    private static void updatePassenger(int ID, String FirstName, String LastName, int CheckInLocationID, String DateTime) {
        Passenger passenger;
        passenger = new Passenger(ID, FirstName, LastName, CheckInLocationID, DateTime);
        PassengerDAO.update(passenger);
    }
    
    private static void deletePassenger(int ID, String FirstName, String LastName, int CheckInLocationID, String DateTime) {
        Passenger passenger;
        passenger = new Passenger(ID, FirstName, LastName, CheckInLocationID, DateTime);
        PassengerDAO.delete(passenger);
    }
    
    static Passenger getPassenger(int id) {
        Optional<Passenger> passengers = PassengerDAO.get(id);
        return passengers.orElseGet(() -> new Passenger(-1, "Non-exist", "Non-exist", -1, "Non-exist"));
    }
    
    //method to clear the CheckInLocation txt fields
    private void clearCheckInLocationTextFields() {
        jTextFieldCINID.setText("");
        jTextFieldCINStationName.setText("");
    }
    
    //method to clear the Passenger txt fields
    private void clearPassengerTextFields() {
        jTextFieldPID.setText("");
        jTextFieldPFirstName.setText("");
        jTextFieldPLastName.setText("");
        jTextFieldPCheckInLocationID.setText("");
        dateTimePickerPassengerDateTime.clear();
       
    }
    
    private void refreshCheckInLocationTable() {
        List<CheckInLocation> checkInLocations = CheckInLocationDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTableCheckInLocation.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (CheckInLocation CheckInLocation : checkInLocations) {
                Object[] row = new Object[2];
                row[0] = CheckInLocation.getCheckInLocationID();
                row[1] = CheckInLocation.getStationName();
                model.addRow(row);
        }
    }
    
    private void refreshPassengerTable() {
        List<Passenger> passengers = PassengerDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTablePassenger.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (Passenger Passenger : passengers) {
                Object[] row = new Object[5];
                row[0] = Passenger.getPassengerID();
                row[1] = Passenger.getFirstName();
                row[2] = Passenger.getLastName();
                row[3] = Passenger.getCheckInLocationID();
                row[4] = Passenger.getCheckInDatetime();
                model.addRow(row);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        CheckInLocationDAO = new CheckInLocationDAO();
        PassengerDAO= new PassengerDAO();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePickerPassengerDateTime;
    private javax.swing.JButton jButtonCINDelete;
    private javax.swing.JButton jButtonCINSave;
    private javax.swing.JButton jButtonCINUpdate;
    private javax.swing.JButton jButtonPDelete;
    private javax.swing.JButton jButtonPSave1;
    private javax.swing.JButton jButtonPUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCINID;
    private javax.swing.JLabel jLabelCINStationName;
    private javax.swing.JLabel jLabelPCheckinLocationID;
    private javax.swing.JLabel jLabelPDateTime;
    private javax.swing.JLabel jLabelPFirstname;
    private javax.swing.JLabel jLabelPID;
    private javax.swing.JLabel jLabelPLastName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCheckInLocation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneAirpotCRUD;
    private javax.swing.JTable jTableCheckInLocation;
    private javax.swing.JTable jTablePassenger;
    private javax.swing.JTextField jTextFieldCINID;
    private javax.swing.JTextField jTextFieldCINStationName;
    private javax.swing.JTextField jTextFieldPCheckInLocationID;
    private javax.swing.JTextField jTextFieldPFirstName;
    private javax.swing.JTextField jTextFieldPID;
    private javax.swing.JTextField jTextFieldPLastName;
    // End of variables declaration//GEN-END:variables
}
